### PR TITLE
    appchooserdialog: avoid crash when there are few app options

### LINKED ISSUE #302: App chooser dialog crash (OOB read) in ensure_default_is_below()
After fixing https://github.com/flatpak/xdg-desktop-portal/issues/480, xdg-desktop-portal-gtk crashes when trying to open an image file. Problem is the code reads off the end of the choices list when the number of choices is less than `INITIAL_LIST_SIZE - 1`:

```
#0  __strcmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:101
#1  0x00000000004130f4 in ensure_default_is_below (num=3, default_id=0x4da370 "eog", choices=0x4f6770)
    at src/appchooserdialog.c:334
        i = 3
        dialog = 0x7e02e0 [AppChooserDialog]
        n_choices = <optimized out>
        i = <optimized out>
        short_location = <optimized out>
#2  app_chooser_dialog_new
    (choices=choices@entry=0x4f6770, default_id=0x4da370 "eog", content_type=<optimized out>, location=0x4da3a8 "Screenshot from 2020-04-13 14-14-54(3).png") at src/appchooserdialog.c:387
        dialog = 0x7e02e0 [AppChooserDialog]
        n_choices = <optimized out>
        i = <optimized out>
        short_location = <optimized out>
#3  0x000000000040fe01 in handle_choose_application
    (object=0x55a5b0, invocation=0x7fffdc00deb0 [GDBusMethodInvocation], arg_handle=<optimized out>, arg_app_id=<optimized out>, arg_parent_window=<optimized out>, choices=0x4f6770, arg_options=0x7bd200) at src/appchooser.c:199
        request = 0x779e00
        dialog = <optimized out>
        handle = <optimized out>
        sender = <optimized out>
        latest_chosen_id = 0x4da370 "eog"
        content_type = 0x4da388 "image/png"
        location = 0x4da3a8 "Screenshot from 2020-04-13 14-14-54(3).png"
        modal = 1
        display = <optimized out>
        screen = <optimized out>
        external_parent = <optimized out>
        fake_parent = 0x4f0500 [GtkWindow]
#4  0x00007ffff64a0af0 in ffi_call_unix64 () at ../src/x86/unix64.S:76
#5  0x00007ffff64a02ab in ffi_call
    (cif=cif@entry=0x7fffffffcf60, fn=fn@entry=0x40fcb0 <handle_choose_application>, rvalue=<optimized out>, avalue=avalue@entry=0x7fffffffce50) at ../src/x86/ffi64.c:525
        classes = {X86_64_INTEGER_CLASS, X86_64_NO_CLASS, 4294954752, 32767}
        stack = <optimized out>
        argp = 0x7fffffffcd50 "\n"
        arg_types = <optimized out>
        gprcount = 6
        ssecount = <optimized out>
        ngpr = 1
        nsse = 0
        i = <optimized out>
        avn = <optimized out>
        ret_in_memory = <optimized out>
        reg_args = <optimized out>
#8  0x00007ffff709a463 in <emit signal ??? on instance 0x55a5b0 [XdpImplAppChooserSkeleton]>
    (node=<optimized out>, detail=0, instance=0x55a5b0, emission_return=0x7fffffffd180, instance_and_params=0x7efad0)
    at ../gobject/gsignal.c:3742
        tmp = <optimized out>
        handler = 0x5b2540
        accumulator = 0x5756b0
--Type <RET> for more, q to quit, c to continue without paging--c
        emission = {next = 0x0, instance = 0x55a5b0, ihint = {signal_id = 192, detail = 0, run_type = G_SIGNAL_RUN_FIRST}, state = EMISSION_RUN, chain_type = 0x4 [void]}
        hlist = <optimized out>
        handler_list = 0x5b2540
        return_accu = 0x7fffffffd100
        accu = {g_type = 0x14 [gboolean], data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        signal_id = 192
        max_sequential_handler_number = 318
        return_value_altered = <optimized out>
    #6  0x00007ffff708838d in g_cclosure_marshal_generic (closure=<optimized out>, return_gvalue=<optimized out>, n_param_values=<optimized out>, param_values=<optimized out>, invocation_hint=<optimized out>, marshal_data=<optimized out>) at ../gobject/gclosure.c:1500
                rtype = <optimized out>
                rvalue = 0x7fffffffcef0
                n_args = <optimized out>
                atypes = <optimized out>
                args = <optimized out>
                i = <optimized out>
                cif = {abi = FFI_UNIX64, nargs = 8, arg_types = 0x7fffffffcea0, rtype = 0x7ffff64a10c0 <ffi_type_sint32>, bytes = 16, flags = 10}
                cc = <optimized out>
                enum_tmpval = 0x7fffffffcf00
                tmpval_used = 0
    #7  0x00007ffff708788a in g_closure_invoke (closure=0x595170, return_value=return_value@entry=0x7fffffffd100, n_param_values=7, param_values=param_values@entry=0x7efad0, invocation_hint=invocation_hint@entry=0x7fffffffd0e0) at ../gobject/gclosure.c:810
                marshal = 0x40c870 <g_cclosure_marshal_generic@plt>
                marshal_data = 0x0
                in_marshal = 0
                real_closure = 0x595150
                __func__ = "g_closure_invoke"
#9  0x0000000000428080 in _xdp_impl_app_chooser_skeleton_handle_method_call (connection=<optimized out>, sender=<optimized out>, object_path=<optimized out>, interface_name=0x7fffd80064e0 "org.freedesktop.impl.portal.AppChooser", method_name=0x7fffd8057e50 "ChooseApplication", parameters=<optimized out>, invocation=0x7fffdc00deb0 [GDBusMethodInvocation], user_data=0x55a5b0) at src/xdg-desktop-portal-dbus.c:3209
        skeleton = <optimized out>
        info = 0x468780 <_xdp_impl_app_chooser_method_info_choose_application>
        iter = {x = {7998096, 5, 5, 0, 5612976, 188, 5728144, 3579507750, 0, 140737338013211, 0, 140737338013295, 5570992, 16985534823608123904, 5583544, 5581840}}
        child = 0x0
        paramv = 0x7efad0
        num_params = <optimized out>
        n = <optimized out>
        signal_id = 192
        return_value = {g_type = 0x14 [gboolean], data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        __func__ = "_xdp_impl_app_chooser_skeleton_handle_method_call"
#10 0x00007ffff71f8ee1 in g_dbus_interface_method_dispatch_helper (interface=<optimized out>, method_call_func=0x427ee0 <_xdp_impl_app_chooser_skeleton_handle_method_call>, invocation=0x7fffdc00deb0 [GDBusMethodInvocation]) at ../gio/gdbusinterfaceskeleton.c:613
        has_handlers = <optimized out>
        has_default_class_handler = <optimized out>
        emit_authorized_signal = <optimized out>
        run_in_thread = <optimized out>
        flags = <optimized out>
        object = 0x0
        __func__ = "g_dbus_interface_method_dispatch_helper"
#11 0x00007ffff71dead2 in call_in_idle_cb (user_data=user_data@entry=0x7fffdc00deb0) at ../gio/gdbusconnection.c:4888
        invocation = 0x7fffdc00deb0 [GDBusMethodInvocation]
        vtable = <optimized out>
        registration_id = <optimized out>
        subtree_registration_id = <optimized out>
        __func__ = "call_in_idle_cb"
#12 0x00007ffff6f9749b in g_idle_dispatch (source=source@entry=0x7fffd800bb00, callback=0x7ffff71de9a0 <call_in_idle_cb>, user_data=0x7fffdc00deb0) at ../glib/gmain.c:5755
        again = <optimized out>
#13 0x00007ffff6f9b7cf in g_main_dispatch (context=0x4d5250) at ../glib/gmain.c:3309
        dispatch = <optimized out>
        prev_source = 0x0
        was_in_call = <optimized out>
        user_data = 0x7fffdc00deb0
        callback = 0x7ffff71de9a0 <call_in_idle_cb>
        cb_funcs = 0x7ffff7072280 <g_source_callback_funcs>
        cb_data = 0x7fffd8057dd0
        need_destroy = <optimized out>
        source = 0x7fffd800bb00
        current = 0x4d5340
        i = 0
        __func__ = "g_main_dispatch"
#14 g_main_context_dispatch (context=0x4d5250) at ../glib/gmain.c:3974
#15 0x00007ffff6f9bb58 in g_main_context_iterate (context=0x4d5250, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4047
        max_priority = 2147483647
        timeout = -1
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = <optimized out>
        fds = 0x638670
#16 0x00007ffff6f9be73 in g_main_loop_run (loop=0x638690) at ../glib/gmain.c:4241
        __func__ = "g_main_loop_run"
#17 0x000000000040d697 in main (argc=<optimized out>, argv=<optimized out>) at src/xdg-desktop-portal-gtk.c:289
        owner_id = 1
        error = 0x0
        session_bus = <optimized out>
        context = 0x571c00
```

### PR DESCRIPTION
**Pull request by mcatanzaro**
Problem is the code reads off the end of the choices list when the number of choices is less than `INITIAL_LIST_SIZE - 1`.
    
Fixes #302

### CODE REVIEW

File: src/appchooserdialog.c [hunk 1]
```diff
@@ -132,6 +132,12 @@ show_more (AppChooserDialog *dialog)
   gtk_window_set_resizable (GTK_WINDOW (dialog), TRUE);
   gtk_widget_hide (dialog->more_row);
 
+  for (i = 0; i < INITIAL_LIST_SIZE - 1; i++)
```
Comment (hadess) [inline src/appchooserdialog.c:135]: Use `g_strv_length()` instead.

File: src/appchooserdialog.c [hunk 2]
```diff
@@ -384,11 +390,11 @@ app_chooser_dialog_new (const char **choices,
       gtk_label_set_label (GTK_LABEL (dialog->heading), _("Choose an application."));
     }
 
-  ensure_default_is_below (choices, default_id, INITIAL_LIST_SIZE - 1);
-
   dialog->choices = g_strdupv ((char **)choices);
-
   n_choices = g_strv_length ((char **)choices);
```
Comment (hadess) [inline src/appchooserdialog.c:394]: (like here)

File: src/appchooserdialog.c [hunk 3]
```diff
@@ -384,11 +384,11 @@ app_chooser_dialog_new (const char **choices,
...
+
+  ensure_default_is_below (choices, default_id, MIN (n_choices, INITIAL_LIST_SIZE - 1));
```
Comment (hadess) [inline src/appchooserdialog.c:396]: Would be good to add guards in `ensure_default_is_below()`, or at least make it more resilient by removing the "num" argument and calculating it as needed.

File: src/appchooserdialog.c (hunk 1 above)
Comment (mcatanzaro) [reply src/appchooserdialog.c:135]: Much better. Not sure what I was thinking. :S

File: src/appchooserdialog.c (hunk 3 above)
Comment (mcatanzaro) [reply src/appchooserdialog.c:396]: OK, good point.

File: src/appchooserdialog.c (hunk 1 above)
Comment (mcatanzaro) [reply src/appchooserdialog.c:135]: Actually I will use an assert() here instead. It's guaranteed that we always have more choices than INITIAL_LIST_SIZE if we reach this function.

Comment (hadess) [reply src/appchooserdialog.c:135]: A `g_warning()` or a `g_return_val_if_fail()` would be better, the app calling the portal isn't responsible for bugs in the code, and there are other apps that might be using the portal...

**Comment by mcatanzaro** [comment]
Note that the reworked MR changes INITIAL_LIST_SIZE from 4 to 3 to make the code easier to read (no behavior change there).

File: src/appchooserdialog.c (hunk 1 above)
Comment (mcatanzaro) [reply src/appchooserdialog.c]: Well this function will only ever be called when there are more apps available than fit in the initial list. So an assert is appropriate here: it will only be hit if there is a bug in xdg-desktop-chooser-gtk itself.

**Comment by hadess** [comment]
> Note that the reworked MR changes INITIAL_LIST_SIZE from 4 to 3 to make the code easier to read (no behavior change there).

This should really be done separately. Ideally, you'd introduce a new variable (`INITIAL_LIST_MAX_INDEX` for example), and use it in all the places, then make the behavioural changes.

File: src/appchooserdialog.c [hunk 4]
```diff
@@ -132,7 +132,9 @@ show_more (AppChooserDialog *dialog)
   gtk_window_set_resizable (GTK_WINDOW (dialog), TRUE);
   gtk_widget_hide (dialog->more_row);
 
-  for (i = INITIAL_LIST_SIZE - 1; dialog->choices[i]; i++)
+  g_assert (g_strv_length ((char **)dialog->choices) > INITIAL_LIST_SIZE);
```
Comment (hadess) [inline src/appchooserdialog.c:135]: `g_return_if_fail()`, as mentioned, we want to avoid xdg-desktop-portal crashing for all users because of a programmer bug.

Comment (mcatanzaro) [reply src/appchooserdialog.c:135]: As you prefer.

**Comment by mcatanzaro** [comment]
> This should really be done separately. Ideally, you'd introduce a new variable (`INITIAL_LIST_MAX_INDEX` for example), and use it in all the places, then make the behavioural changes.

Well we don't need any new variable?

I can split it out to a new MR if you want. Basically I did the exact opposite here: I made my behavior change first, then cleanups afterwards. They're all separate commits, isn't that fine?

**Comment by mcatanzaro** [comment]
To be clear: first commit is the crash fix, next three commits are just related cleanups that could be split.

**Comment by hadess** [comment]
> Well we don't need any new variable?

It's supposed to be the number of items to show before "show more" is shown. It's not an index, and it just seems that you're changing the variable for no reason. Because when someone goes back to this code in a year and sees the code they'll wonder why the code says "3 items before show more" but shows 4.

**Comment by hadess** [comment]
I re-read the commit messages, and I guess the changes make more sense than what was there before.

File: src/appchooserdialog.c [hunk 5]
```diff
@@ -132,6 +132,8 @@ show_more (AppChooserDialog *dialog)
   gtk_window_set_resizable (GTK_WINDOW (dialog), TRUE);
   gtk_widget_hide (dialog->more_row);
 
+  g_return_if_fail (g_strv_length ((char **)dialog->choices) > INITIAL_LIST_SIZE);
```
Comment (hadess) [inline src/appchooserdialog.c:135]: Space after the cast's parens:
`g_return_if_fail (g_strv_length ((char **) dialog->choices) > INITIAL_LIST_SIZE);`

Can you also update the commit message to not mention assertions?

File: src/appchooserdialog.c [hunk 6]
```diff
@@ -316,22 +316,26 @@ shorten_location (const char *location)
...
 
 static void
-ensure_default_is_below (const char **choices,
-                         const char  *default_id,
-                         int          num)
+ensure_default_in_initial_list (const char **choices,
+                                const char  *default_id)
 {
   int i;
+  int n_choices;
```
Comment (hadess) [inline src/appchooserdialog.c:323]: guint.

File: src/appchooserdialog.c [hunk 7]
```diff
@@ -386,11 +390,11 @@ app_chooser_dialog_new (const char **choices,
...
     }
 
-  dialog->choices = g_strdupv ((char **)choices);
-  n_choices = g_strv_length ((char **)choices);
+  ensure_default_in_initial_list (choices, default_id);
 
-  ensure_default_is_below (dialog->choices, default_id, MIN (n_choices, INITIAL_LIST_SIZE));
+  dialog->choices = g_strdupv ((char **)choices);
 
+  n_choices = g_strv_length ((char **)choices);
```
Comment (hadess) [inline src/appchooserdialog.c]: Space after the cast.

**Comment by hadess** [comment]
Looks fine to push after those nits are fixed, thanks.

File: src/appchooserdialog.c (hunk 5 above)
Comment (mcatanzaro) [reply src/appchooserdialog.c:135]: g_return is an assertion, but I can reword it, sure.

**Comment by mcatanzaro** [comment]
> It's supposed to be the number of items to show before "show more" is shown. It's not an index, 

Agreed, my change makes this true.

> and it just seems that you're changing the variable for no reason. Because when someone goes back to this code in a year and sees the code they'll wonder why the code says "3 items before show more" but shows 4.

It should show three before and after this change. Was really confusing for INITIAL_LIST_SIZE to not match that. :)

File: src/appchooserdialog.c (hunk 5 above)
Comment (mcatanzaro) [reply src/appchooserdialog.c:135]: This file doesn't use spaces after casts. Let's change that in a follow-up if you prefer it that way.

File: src/appchooserdialog.c (hunk 7 above)
Comment (mcatanzaro) [reply src/appchooserdialog.c]: OK.

Comment (mcatanzaro) [reply src/appchooserdialog.c]: Sorry, let's change this in a follow-up because the surrounding code does not use casts here. It feels weird to contradict that.

File: src/appchooserdialog.c (hunk 5 above)
Comment (hadess) [reply src/appchooserdialog.c:135]: OK for the spaces after casts. As for the g_return, it's a guard, not an assertion (which would call `abort()` on failure) ;)

Comment (mcatanzaro) [reply src/appchooserdialog.c:135]: "Assertion guard?" Point is it's a statement that should never fail except in case of programmer error. Whatever, we know how it works. :)
