### PR TITLE
wallpaper: Fix misuse of picture-uri gsetting

### LINKED ISSUE #374: wallpaper: Mishandling of picture-uri
x-d-p-gtk's wallpaper code seems to mishandle the `picture-uri` setting in two ways:

1. It inserts a raw path into `picture-uri`, and not a URI. I assume this happens to work with mutter, but any other app expecting to read a URI from `picture-uri` won't fare too well with this.
2. It always copies the wallpaper into `~/.config/background`. This means that if the portal is used to set the wallpaper twice in a row, the second wallpaper change _won't_ change the `picture-uri` setting. Therefore, an app monitoring `picture-uri` for changes will never be notified that the wallpaper changed.

### PR DESCRIPTION
**Pull request by felipeborges**
The Portal was setting the org.gnome.desktop.background picture-uri gsetting to a path, when applications expect an URI.

Fixes #374

### CODE REVIEW

File: src/wallpaper.c [hunk 1]
```diff
@@ -130,8 +130,10 @@ set_wallpaper (WallpaperDialogHandle *handle,
                const gchar *uri)
 {
   g_autoptr(GFile) source = NULL;
+  const gchar *path;
```
Comment (TingPing) [inline src/wallpaper.c:133]:
```suggestion
  g_autofree gchar *path = NULL;
```

File: src/wallpaper.c [hunk 2]
```diff
@@ -130,8 +130,10 @@ set_wallpaper (WallpaperDialogHandle *handle,
...
 
-  handle->picture_uri = g_build_filename (g_get_user_config_dir (), "background", NULL);
+  path = g_build_filename (g_get_user_config_dir (), "background", NULL);
+  handle->picture_uri = g_filename_to_uri (path, NULL, NULL);
```
Comment (TingPing) [inline src/wallpaper.c:136]: This value can be `NULL` now. The `g_file_new_for_uri` above does not handle this and it silently fails here.

Comment (felipeborges) [reply src/wallpaper.c:136]: Do you think we could simply `g_assert (uri != NULL)`  above g_file_new_for_uri as it would be considered a client error to provide an invalid uri?

Comment (TingPing) [reply src/wallpaper.c:136]: Well it wouldn't be a client error. It would be a user using an encoding with characters that cannot be represented in UTF-8.

This should be extremely rare but possible. I would handle the `GError`, print out a warning, and return without doing anything.

Comment (matthiasclasen) [reply src/wallpaper.c:136]: Asserting can never be right - it'll make the portal crash on a client error
